server:
  port: 6666

spring:
  profiles:
    active: prod
  redis:
    timeout: 6000ms
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 10
    host: ${spring.redis.host}
    port: ${spring.redis.port}

bloom:
  filter:
    size: ${bloom.filter.size}
    fpp: ${bloom.filter.fpp}



dubbo:
  registry:
    protocol: zookeeper
    address: ${dubbo.registry.address}
    id: registry
    client: zkclient
    timeout: 100000
    file: ${dubbo.home}/frequency_control_dubbo/dubbo-registry.properties
  protocol:
    port: 21001
    name: dubbo
    id: dubbo
    status: server
    server: netty
  application:
    name: frequency-control-provider
    id: frequency-control-provider
    qosEnable: true
    qosPort: 23333
    qosAcceptForeignIp: false
  consumer:
    timeout: 3000
    check: false